- name: Add DB Access For This Node
  include_role:
    name: part20-config-pg-hba
    apply:
      throttle: 1
  vars:
    server_ip: "{{item.server}}"
    config_path: "{{item.configpath}}"
    source_ip: "{{ inventory_hostname }}"
    pg_version: "{{item.version}}"
  with_items: "{{ pg_db_list }}"