- name: Debian-Based | Update apt package index and install necessary packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Debian-Based | Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    
- name: Extract the Architecture of host
  shell: "dpkg --print-architecture"
  register: architecture

- name: Debian-Based | Add Docker apt repository
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Debian-Based | Install Docker packages
  apt:
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    state: present
    update_cache: yes

- name: Debian-Based | Verify Docker installation
  command: docker run hello-world
  register: result
  ignore_errors: true

- name: Debian-Based | Docker Installation Status
  debug:
    var: result.stdout_lines
