- name: Upgrade debian family.
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Update all packages to their latest version
  apt:
    name: '*'
    state: latest

- name: Update packages to latest version.
  apt:
    upgrade: dist
    force_apt_get: yes
