- name: Ensure old versions of Docker are not installed
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker.io
    - docker-engine

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: True

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: "present"
