---
- name: Installation for client
  apt:
        name: "{{ item }}"
        state: present
  loop:
        - firewalld
        - nfs-common


- name: Enable and Start Services
  service:
        name: "{{ item }}"
        enabled: yes
        state: started
  loop:
        - firewalld
        - nfs-common


- name: Allow ssh and nfs service over firewall
  firewalld:
        service: "{{ item }}"
        permanent: yes
        zone: public
        state: enabled
        immediate: true
  loop:
        - ssh
        - nfs


- name: Create the shared directory
  file:
        path: /home/data1
        state: directory
        owner: nobody
        group: nogroup
        mode: 0755


- name: create exports
  file:
        path: /etc/exports
        state: touch


- name: Config 
  ansible.builtin.lineinfile:
        line: "/home/data1 {{ item }}(rw,sync,no_root_squash,no_subtree_check)"
        path: /etc/exports
  with_items:
        - "{{ groups.nfs_server}}"


- name: mount the nfs
  mount:
        src: "{{ item }}:/home/data1"
        path: /home/data1
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
  with_items:
        - "{{ groups.nfs_server}}"




