---
# tasks file for part18-package-manager
- name: Set apt proxy config
  copy:
    src: 05proxy
    dest: /etc/apt/apt.conf.d/05proxy
    mode: 0644
  when:
    - (ansible_distribution|string == 'Ubuntu' or ansible_distribution|string == 'Debian')
    
- name: Installing APT pkgs
  apt:
    force: yes
    autoremove: yes
    pkg: "{{ pkgs_list }}"
 # with_items: "{{ pkgs_list }}"
  when:
    - (ansible_distribution|string == 'Ubuntu' or ansible_distribution|string == 'Debian')
    - action == "install"

- name: Update and Upgrade APT pkgs
  apt:
    update_cache: true
    upgrade: true
    dpkg_options: 'force-confold,force-confdef'
    autoremove: true
  when:
    - (ansible_distribution|string == 'Ubuntu') or (ansible_distribution|string == 'Debian')
    - action == "update"

- name: Check Reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_status

- name: Get Confirm Reboot
  pause:
    prompt: " {{ inventory_hostname }} reboot required, please confirm reboot now: (yes or no):"
    echo: true
  register: confirm
  when:
    - reboot_status.stat.exists

- set_fact:
    reboot_confirm: "{{ confirm.user_input }}" 
  when:
    - reboot_status.stat.exists

- name: Reboot Server
  reboot:
    reboot_timeout: 600
  when: 
    - reboot_status.stat.exists
    - reboot_confirm == True
